"code" => $produtos[0]['cProd'],
        //             "description" => $produtos[0]['xProd'],
        //             "quantity" => $qtdVolume,
        //             "price" => $valorTotal,
        //             "length" => 0,
        //             "width" => 0,
        //             "height" => 0,
        //             "weight" => 0,
        //             "cubicWeight" => 0